Repository saurabh0719/elara, pull requests merged in 2021-05, with the labels that each got.

#4 v0.2.0
  README.md
  README.rst
  elara/__init__.py
  elara/elara.py
  elara/hashtables.py
  elara/lists.py
  elara/lru.py
  elara/shared.py
  elara/strings.py
  setup.py
  test/test_1.py
  test/test_LRU.py
Labels: documentation, enhancement

#12 Move storage format over to binary, this change allows the addition of:
  elara/elara.py
  elara/elarautil.py
  elara/exceptions.py
  elara/shared.py
  requirements.txt
  setup.py
  test/test_1.py
Labels: enhancement

#15 V0.4.0 develop - Re-architect cache core to account for cache params
  .github/workflows/test.yml
  elara/__init__.py
  elara/elara.py
  elara/hashtables.py
  elara/lists.py
  elara/lru.py
  elara/shared.py
  elara/status.py
  elara/strings.py
  settings.json
  test/test_1.py
  test/test_4.py
  test/test_LRU.py
  test/test_cache.py
  test/test_exe.py
Labels: enhancement

#17 V0.5.1 release
  README.md
  README.rst
  elara/elara.py
  elara/exceptions.py
  elara/hashtables.py
  elara/lists.py
  elara/status.py
  settings.json
  setup.py
  test/test_1.py
  test/test_2.py
  test/test_3.py
  test/test_4.py
  test/test_cache.py
Labels: bug fix, enhancement

#18 updated docs
  README.md
Labels: documentation
